# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71eaeeefb3543587786537e46abff8f42bde80f0c1fb62f2e981a5edb2846e930c18363ddce910fb7979b18e2c8c6d8dcbea748dd1b591e72d043258714d9e67

test:
  secret_key_base: b32606427eb358587e103509246ee23fa28d7a7e12ef7e536ab0ab5304965d549ae7543eaf202e4f560b789c76d5e2e170e31735838a66aad6b6916eb2f293c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
